name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    uses: Kowada-GmbH/github-workflows/.github/workflows/symfony-bundle-ci.yml@master
